
import com.sun.glass.events.KeyEvent;
import java.util.Stack;
import tubes.tba.TUBESTBA;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author divin
 */
public class Tampilan extends javax.swing.JFrame {

    /**
     * Creates new form Tampilan
     */
       
        private static Stack<String> PDA = new Stack();
        
        private String SPOK = "";
    public Tampilan() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        checkBT = new javax.swing.JButton();
        inputan = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputan = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        checkBT.setFont(new java.awt.Font("Georgia", 0, 13)); // NOI18N
        checkBT.setText("CHECK");
        checkBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                checkBTMousePressed(evt);
            }
        });

        inputan.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        inputan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputanKeyPressed(evt);
            }
        });

        outputan.setColumns(20);
        outputan.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        outputan.setRows(5);
        jScrollPane2.setViewportView(outputan);

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel1.setText("MASUKKAN INPUTAN :");

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel2.setText("WELCOME TO \"S-P-O-K\" CHECKER!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkBT, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputan)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(73, 73, 73))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputan, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(checkBT, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkBTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkBTMousePressed
        // TODO add your handling code here:
        outputan.setText(inputan.getText()+"\n"+tampil(inputan.getText()));
        
    }//GEN-LAST:event_checkBTMousePressed

    private void inputanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputanKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            outputan.setText(inputan.getText()+"\n"+tampil(inputan.getText()));
        }
    }//GEN-LAST:event_inputanKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tampilan().setVisible(true);
            }
        });
    }
    
    public static boolean cekSubjek(String[] ArrayKalimat){
        boolean a = false;
        if(ArrayKalimat[0] != null){
            if (ArrayKalimat[0].charAt(0) =='A') {
                if(ArrayKalimat[0].charAt(1)=='K'){
                    if(ArrayKalimat[0].charAt(2)=='U'){
                        a=true;
                    }
                }
             
            }else if(ArrayKalimat[0].charAt(0)=='K'){
                if(ArrayKalimat[0].charAt(1)=='A'){
                    if(ArrayKalimat[0].charAt(2)=='M'){
                        if(ArrayKalimat[0].charAt(3)=='U'){
                            a=true; 
                        }
                    }
                }
            }else if(ArrayKalimat[0].charAt(0)=='D'){
                if(ArrayKalimat[0].charAt(1)=='I'){
                    if(ArrayKalimat[0].charAt(2)=='A'){
                        a=true;
                    }

                }
            }else if(ArrayKalimat[0].charAt(0)=='P'){
                if(ArrayKalimat[0].charAt(1)=='A'){
                    if(ArrayKalimat[0].charAt(2)=='P'){
                        if(ArrayKalimat[0].charAt(3)=='A'){
                            a=true;
                        }
                    }
                }
            }else if(ArrayKalimat[0].charAt(0)=='S'){
                if(ArrayKalimat[0].charAt(1)=='A'){
                    if(ArrayKalimat[0].charAt(2)=='Y'){
                        if(ArrayKalimat[0].charAt(3)=='A'){
                            a=true;
                        }
                    }
                }
            }
        }
        return a;
    }
    public static boolean cekPredikat(String[] ArrayKalimat){
        boolean a = false;
        if(ArrayKalimat[1] != null){
            if(ArrayKalimat[1].charAt(0) =='M'){
                if(ArrayKalimat[1].charAt(1)== 'A'){
                    if(ArrayKalimat[1].charAt(2)=='K'){
                        if(ArrayKalimat[1].charAt(3)=='A'){
                            if(ArrayKalimat[1].charAt(4)=='N'){
                                a=true;
                            }
                        }     
                    }
                
        }else if(ArrayKalimat[1].charAt(1)=='I'){
                if(ArrayKalimat[1].charAt(2)=='N'){
                    if(ArrayKalimat[1].charAt(3)=='U'){
                        if(ArrayKalimat[1].charAt(4)=='M'){
                            a=true;            
                        }               
                    } else if(ArrayKalimat[1].charAt(3)=='T'){
                    if(ArrayKalimat[1].charAt(4)=='A'){
                            a=true;                                    
                    }
                }
                }        
        }else if(ArrayKalimat[1].charAt(1)=='E'){
                if(ArrayKalimat[1].charAt(2)=='N'){
                    if(ArrayKalimat[1].charAt(3)=='U'){
                        if(ArrayKalimat[1].charAt(4)=='L'){
                            if(ArrayKalimat[1].charAt(5)=='I'){
                                if(ArrayKalimat[1].charAt(6)=='S'){
                                    a=true;             
                                }               
                            }               
                        }         
                    }
                }
        }
       }else if(ArrayKalimat[1].charAt(0)=='T'){
            if(ArrayKalimat[1].charAt(1)=='I'){
                if(ArrayKalimat[1].charAt(2)=='D'){
                    if(ArrayKalimat[1].charAt(3)=='U'){
                        if(ArrayKalimat[1].charAt(4)=='R'){
                            a=true;             
                        }         
                    }
                }
            }
        }
        }  
        return a;
    }
    
    public static boolean cekObjek(String[] ArrayKalimat){
        boolean a = false;
        if(ArrayKalimat[2] != null){
            if(ArrayKalimat[2].charAt(0) =='N'){
                if(ArrayKalimat[2].charAt(1)== 'A'){
                    if(ArrayKalimat[2].charAt(2)=='S'){
                        if(ArrayKalimat[2].charAt(3)=='I'){
                                a=true;
                        }     
                    }
                }
        }else if(ArrayKalimat[2].charAt(0)=='A'){
                if(ArrayKalimat[2].charAt(1)=='I'){
                    if(ArrayKalimat[2].charAt(2)=='R'){
                        a=true;             
                    }
                }   
        }else if(ArrayKalimat[2].charAt(0)=='B'){
                if(ArrayKalimat[2].charAt(1)=='O'){
                    if(ArrayKalimat[2].charAt(2)=='L'){
                        if(ArrayKalimat[2].charAt(3)=='A'){
                            a=true;              
                        }               
                    }
                }
        }else if(ArrayKalimat[2].charAt(0)=='E'){
                if(ArrayKalimat[2].charAt(1)=='S'){
                    if(ArrayKalimat[2].charAt(2)=='S'){
                        if(ArrayKalimat[2].charAt(3)=='A'){
                            if(ArrayKalimat[2].charAt(4)=='Y'){
                                    a=true;         
                            }               
                        }         
                    }
                }
        }else if(ArrayKalimat[2].charAt(0)=='S'){
            if(ArrayKalimat[2].charAt(1)=='I'){
                if(ArrayKalimat[2].charAt(2)=='A'){
                    if(ArrayKalimat[2].charAt(3)=='N'){
                        if(ArrayKalimat[2].charAt(4)=='G'){
                            a=true;               
                        }         
                    }
                }
            }
        }
        }
        return a;
    }
    public static boolean cekKeterangan(String[] ArrayKalimat){
        boolean a = false;
        if(ArrayKalimat[3] != null){
            if(ArrayKalimat[3].charAt(0) =='D'){
                if(ArrayKalimat[3].charAt(1)== 'I'){
                    if(ArrayKalimat[3].charAt(2)=='R'){
                        if(ArrayKalimat[3].charAt(3)=='U'){
                            if(ArrayKalimat[3].charAt(4)=='M'){
                                if(ArrayKalimat[3].charAt(5)=='A'){
                                    if(ArrayKalimat[3].charAt(6)=='H'){
                                        a=true;
                                    }
                                }
                            }
                        }     
                }else if(ArrayKalimat[3].charAt(2)=='D'){
                        if(ArrayKalimat[3].charAt(3)=='A'){
                            if(ArrayKalimat[3].charAt(4)=='P'){
                                if(ArrayKalimat[3].charAt(5)=='U'){
                                    if(ArrayKalimat[3].charAt(6)=='R'){
                                        a=true;
                                    }
                                }
                            }
                        }     
                } else if(ArrayKalimat[3].charAt(2)=='K'){
                        if(ArrayKalimat[3].charAt(3)=='A'){
                            if(ArrayKalimat[3].charAt(4)=='M'){
                                if(ArrayKalimat[3].charAt(5)=='A'){
                                    if(ArrayKalimat[3].charAt(6)=='R'){
                                        a=true;
                                    }
                                }
                            }
                        }     
                } else if(ArrayKalimat[3].charAt(2)=='B'){
                        if(ArrayKalimat[3].charAt(3)=='U'){
                            if(ArrayKalimat[3].charAt(4)=='K'){
                                if(ArrayKalimat[3].charAt(5)=='U'){
                                        a=true;                                 
                                }
                            }
                        }     
                } else if(ArrayKalimat[3].charAt(2)=='T'){
                        if(ArrayKalimat[3].charAt(3)=='A'){
                            if(ArrayKalimat[3].charAt(4)=='M'){
                                if(ArrayKalimat[3].charAt(5)=='A'){   
                                    if(ArrayKalimat[3].charAt(6)=='N'){
                                        a=true;
                                    }
                                }
                            }
                        }     
                }
            }
            }
        }
        return a;
    }
    public static boolean cekKeterangan1(String[] ArrayKalimat){
        boolean a = false;
        if(ArrayKalimat[2] != null){
            if(ArrayKalimat[2].charAt(0) =='D'){
                if(ArrayKalimat[2].charAt(1)== 'I'){
                    if(ArrayKalimat[2].charAt(2)=='R'){
                        if(ArrayKalimat[2].charAt(3)=='U'){
                            if(ArrayKalimat[2].charAt(4)=='M'){
                                if(ArrayKalimat[2].charAt(5)=='A'){
                                    if(ArrayKalimat[2].charAt(6)=='H'){
                                        a=true;
                                    }
                                }
                            }
                        }     
                }else if(ArrayKalimat[2].charAt(2)=='D'){
                        if(ArrayKalimat[2].charAt(3)=='A'){
                            if(ArrayKalimat[2].charAt(4)=='P'){
                                if(ArrayKalimat[2].charAt(5)=='U'){
                                    if(ArrayKalimat[2].charAt(6)=='R'){
                                        a=true;
                                    }
                                }
                            }
                        }     
                } else if(ArrayKalimat[2].charAt(2)=='K'){
                        if(ArrayKalimat[2].charAt(3)=='A'){
                            if(ArrayKalimat[2].charAt(4)=='M'){
                                if(ArrayKalimat[2].charAt(5)=='A'){
                                    if(ArrayKalimat[2].charAt(6)=='R'){
                                        a=true;
                                    }
                                }
                            }
                        }     
                } else if(ArrayKalimat[2].charAt(2)=='B'){
                        if(ArrayKalimat[2].charAt(3)=='U'){
                            if(ArrayKalimat[2].charAt(4)=='K'){
                                if(ArrayKalimat[2].charAt(5)=='U'){
                                        a=true;                                 
                                }
                            }
                        }     
                } else if(ArrayKalimat[2].charAt(2)=='T'){
                        if(ArrayKalimat[2].charAt(3)=='A'){
                            if(ArrayKalimat[2].charAt(4)=='M'){
                                if(ArrayKalimat[2].charAt(5)=='A'){   
                                    if(ArrayKalimat[2].charAt(6)=='N'){
                                        a=true;
                                    }
                                }
                            }
                        }     
                }
            }
            }
        }
        return a;
    }
    
    public boolean outputan (String[] ArrayKalimat){
        boolean a = false;
        SPOK="";
        PDA.push("#");
        PDA.push("Start");
        
        if(ArrayKalimat.length==4){
//            System.out.println("");
//            System.out.println("Pola kalimat :");
            if(cekSubjek(ArrayKalimat)){
            PDA.pop();
            PDA.push("S");
            SPOK+=PDA.pop();
            if(cekPredikat(ArrayKalimat)){
                PDA.push("-P");
                SPOK+=PDA.pop();
                if(cekObjek(ArrayKalimat)){
                    PDA.push("-O");
                    SPOK+=PDA.pop();
                    if(cekKeterangan(ArrayKalimat)){
                            PDA.push("-K");
                            SPOK+=PDA.pop();
                            a=true;
                    }
                }
            
            }
            }
        } else
        if(ArrayKalimat.length==3){
//            System.out.println("");
//            System.out.println("Pola kalimat :");
            if(cekSubjek(ArrayKalimat)){
            PDA.pop();
            PDA.push("S");
            SPOK+=PDA.pop();
            if(cekPredikat(ArrayKalimat)){
                PDA.push("-P");
                SPOK+=PDA.pop();
                if(cekObjek(ArrayKalimat)){
                    PDA.push("-O");
                    SPOK+=PDA.pop();
                    a=true;
                } 
                if(cekKeterangan1(ArrayKalimat)){
                    PDA.push("-K");
                    SPOK+=PDA.pop();
                    a=true;
                }
            
            }
            }
        } else
        if(ArrayKalimat.length==2){
//            System.out.println("");
//            System.out.println("Pola kalimat :");
            if(cekSubjek(ArrayKalimat)){
            PDA.pop();
            PDA.push("S");
            SPOK+=PDA.pop();
            if(cekPredikat(ArrayKalimat)){
                PDA.push("-P");
                SPOK+=PDA.pop();
                a=true;
            }
            }
        }
         

        
//        System.out.println(SPOK);
        return a;
    }
    public String tampil(String kalimat){
        String[] ArrayKalimat = kalimat.split(" ");
        if (outputan(ArrayKalimat)){
            return "\nPola Kalimat :\n"+SPOK+"\n"+"\n"+"Inputan Valid!";
        }else{
            
            return "\n"+"Inputan Tidak Valid!";
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkBT;
    private javax.swing.JTextField inputan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea outputan;
    // End of variables declaration//GEN-END:variables
}
